docker files updating

diff --git a/docker-compose.yml b/docker-compose.yml
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -1,8 +1,118 @@
 services:
-  # DATABASE
+  nginx:
+    build:
+      context: ./backend
+      dockerfile: ./docker/production/nginx/Dockerfile
+    restart: unless-stopped # Automatically restart unless the service is explicitly stopped
+    volumes:
+      # Mount the 'laravel-storage' volume to '/var/www/storage' inside the container.
+      # -----------------------------------------------------------
+      # This volume stores persistent data like uploaded files and cache.
+      # The ':ro' option mounts it as read-only in the 'nginx' service because Nginx only needs to read these files.
+      # The 'php-fpm' service mounts the same volume without ':ro' to allow write operations.
+      # -----------------------------------------------------------
+      - laravel-storage-production:/var/www/storage:ro
+      # SSL сертификаты. 
+      - /etc/letsencrypt:/etc/letsencrypt:ro
+    networks:
+      - wisswan-production
+    ports:
+      # Map port 80 inside the container to the port specified by 'NGINX_PORT' on the host machine.
+      # -----------------------------------------------------------
+      # This allows external access to the Nginx web server running inside the container.
+      # For example, if 'NGINX_PORT' is set to '8080', accessing 'http://localhost:8080' will reach the application.
+      # -----------------------------------------------------------
+      - "${NGINX_PORT:-80}:80"
+      - "443:443"             
+    depends_on:
+      php-fpm:
+        condition: service_healthy # Wait for php-fpm health check
+      frontend:
+        condition: service_started # Wait for php-fpm health check
+
+  # Laravel: route handler
+  php-fpm:
+    # For the php-fpm service, we will create a custom image to install the necessary PHP extensions and setup proper permissions.
+    build:
+      context: ./backend
+      dockerfile: ./docker/common/php-fpm/Dockerfile
+      target: production # Use the 'production' stage in the Dockerfile
+    restart: unless-stopped
+    volumes:
+      - laravel-storage-production:/var/www/storage # Mount the storage volume
+    env_file:
+      - ./backend/.env
+    networks:
+      - wisswan-production
+    healthcheck:
+      test: ["CMD-SHELL", "php-fpm-healthcheck || exit 1"]
+      interval: 10s
+      timeout: 5s
+      retries: 3
+    # The 'depends_on' attribute with 'condition: service_healthy' ensures that
+    # this service will not start until the 'postgres' service passes its health check.
+    # This prevents the application from trying to connect to the database before it's ready.
+    depends_on:
+      db:
+        condition: service_healthy
+
+  # The Laravel 'php-cli' service provides a command-line interface for running Artisan commands and other CLI tasks.
+  # -----------------------------------------------------------
+  # This is useful for running migrations, seeders, or any custom scripts.
+  # It shares the same codebase and environment as the 'php-fpm' service.
+  # -----------------------------------------------------------
+  php-cli:
+    build:
+      context: ./backend
+      dockerfile: ./docker/production/php-cli/Dockerfile
+    tty: true # Enables an interactive terminal
+    stdin_open: true # Keeps standard input open for 'docker exec'
+    env_file:
+      - ./backend/.env
+    networks:
+      - wisswan-production
+
+  laravel-queue:
+    build:
+      context: ./backend
+      dockerfile: ./docker/common/php-fpm/Dockerfile
+      target: production
+    restart: unless-stopped
+    # --tries=2 Если задача упапа, то попробует ещё раз её выполнить
+    # --timeout=20 Если задача выполняется более 20-ти секунд, то ложить её
+    # Переопределяем дефолтную команду php-fpm на запуск воркера Laravel
+    command: php artisan queue:work --verbose --tries=2 --timeout=20
+    env_file:
+      - ./backend/.env
+    volumes:
+      - laravel-storage-production:/var/www/storage
+    networks:
+      - wisswan-production
+    depends_on:
+      db:
+        condition: service_healthy
+
+  laravel-schedule:
+    build:
+      context: ./backend
+      dockerfile: ./docker/common/php-fpm/Dockerfile
+      target: production
+    tty: true
+    restart: always
+    # Переопределяем дефолтную команду php-fpm на запуск воркера Laravel
+    command: php artisan schedule:work
+    env_file:
+      - ./backend/.env
+    volumes:
+      - laravel-storage-production:/var/www/storage
+    networks:
+      - wisswan-production
+    depends_on:
+      db:
+        condition: service_healthy
+
   db:
-    image: mysql:8.0 # Или mariadb:10.6
-    container_name: wisswan-db
+    image: mysql:8.0
     restart: unless-stopped
     environment:
       MYSQL_DATABASE: wisswan           # Имя базы
@@ -14,64 +124,18 @@ services:
       # МАГИЯ ДЛЯ ДАМПА:
       - ./init-db:/docker-entrypoint-initdb.d # Сюда положи свой дамп
     networks:
-      - wisswan-network
+      - wisswan-production
+    # This prevents dependent services from starting before the database is ready.
+    healthcheck:
+      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "admin", "-padmin"]
+      interval: 10s
+      timeout: 5s
+      retries: 5
 
-  # --- СЕРВИС БЭКЕНДА (Laravel) ---
-  backend:
-    env_file:
-      - ./backend/.env
-    build:
-      context: ./backend      # Где искать Dockerfile для этого сервиса
-      dockerfile: Dockerfile  # Имя файла (если оно стандартное, можно не писать)
-    container_name: wisswan-backend
-    restart: unless-stopped   # Перезапускать контейнер, если он упал (но не если вы сами его выключили)
-    
-    # применяю миграции к базе
-    command: >
-      sh -c "until php artisan db:monitor; do
-               echo 'Waiting for database connection...';
-               sleep 2;
-             done;
-             php artisan migrate;
-             php-fpm"
-    depends_on:
-      - db
-    networks:
-      - wisswan-network       # Подключаем к общей сети, чтобы видеть фронтенд и базу
-
-  # Воркер для обработки задач в фоне
-  queue:
-    env_file:
-      - ./backend/.env
-    build:
-      context: ./backend
-      dockerfile: Dockerfile
-    container_name: wisswan-queue
-    restart: unless-stopped
-    # Используем ту же логику ожидания базы, что и в бэкенде
-    # --tries=2 Если задача упапа, то попробует ещё раз её выполнить
-    # --timeout=20 Если задача выполняется более 20-ти секунд, то ложить её
-    command: >
-      sh -c "until php artisan db:monitor; do
-               echo 'Waiting for DB in queue...';
-               sleep 2;
-             done;
-             php artisan queue:work --verbose --tries=2 --timeout=20"
-    volumes:
-      - ./backend:/var/www
-      - /var/www/vendor  # Не дает локальной папке перекрыть папку в контейнере
-    depends_on:
-      - db
-      - backend
-    networks:
-      - wisswan-network
-
-
-   # Node.js service (use with: docker compose up wisswan-frontend --build)
   frontend:
     build:
       context: ./frontend
-      dockerfile: Dockerfile
+      dockerfile: docker/production/Dockerfile
     container_name: wisswan-frontend
     restart: unless-stopped
     environment:
@@ -80,40 +144,56 @@ services:
     ports:
       - "3000:3000" # Пробрасываем порт: [порт на компе]:[порт в контейнере]
     depends_on:
-      - backend               # Фронт не запустится, пока не поднимется бэкенд
+      - php-fpm               # Фронт не запустится, пока не поднимется бэкенд
     networks:
-      - wisswan-network
+      - wisswan-production
+    
+  # postgres:
+  #   image: postgres:18
+  #   restart: unless-stopped
+  #   user: postgres
+  #   ports:
+  #     - "${POSTGRES_PORT}:5432"
+  #   environment:
+  #     - POSTGRES_DB=${POSTGRES_DATABASE}
+  #     - POSTGRES_USER=${POSTGRES_USERNAME}
+  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
+  #   volumes:
+  #     - postgres-data-production:/var/lib/postgresql
+  #   networks:
+  #     - laravel-production
+  #   # Health check for PostgreSQL
+  #   # -----------------------------------------------------------
+  #   # Health checks allow Docker to determine if a service is operational.
+  #   # The 'pg_isready' command checks if PostgreSQL is ready to accept connections.
+  #   # This prevents dependent services from starting before the database is ready.
+  #   # -----------------------------------------------------------
+  #   healthcheck:
+  #     test: ["CMD", "pg_isready"]
+  #     interval: 10s
+  #     timeout: 5s
+  #     retries: 5
 
+  # redis:
+  #   image: redis:alpine
+  #   restart: unless-stopped # Automatically restart unless the service is explicitly stopped
+  #   networks:
+  #     - laravel-production
+  #   # Health check for Redis
+  #   # -----------------------------------------------------------
+  #   # Checks if Redis is responding to the 'PING' command.
+  #   # This ensures that the service is not only running but also operational.
+  #   # -----------------------------------------------------------
+  #   healthcheck:
+  #     test: ["CMD", "redis-cli", "ping"]
+  #     interval: 10s
+  #     timeout: 5s
+  #     retries: 3
 
-  # --- СЕРВИС ВЕБ-СЕРВЕРА (Nginx) ---
-  nginx:
-    image: nginx:alpine       # Берем готовый легкий образ Nginx
-    container_name: wisswan-nginx
-    restart: unless-stopped
-    ports:
-      - "80:80"               
-      - "443:443"             
-    volumes:
-      # Пробрасываем конфиг, который мы написали ранее
-      - ./nginx.conf:/etc/nginx/conf.d/default.conf
-      # Пробрасываем папку бэкенда, чтобы Nginx видел папку public (для картинок и статики)
-      - ./backend:/var/www
-      # SSL сертификаты
-      - /etc/letsencrypt:/etc/letsencrypt:ro
-
-    depends_on:
-      - backend
-      - frontend
-    networks:
-      - wisswan-network
-      
-
-# --- ОБЪЯВЛЕНИЕ ТОМОВ И СЕТЕЙ (строго в начале строки) ---
-volumes:
-  db_data: # Объявляем том в конце файла
-
-
-# Описание сети, в которой будут общаться наши контейнеры
 networks:
-  wisswan-network:
-    driver: bridge # Стандартный драйвер для связи на одном хосте
+  wisswan-production:
+
+volumes:
+  laravel-storage-production:
+  db_data:
+
